package DwgenHTML ;
use warnings;
use strict;
#use File::Copy;
use Dawin;

my ($sheet, $Ftbl, $Fcol, $Flst, $src_path, $wdir, $sfile, $ftype, $First_html, $T_COUNT);

sub start {
		( $src_path, $wdir, $sfile, $ftype) = @_; #소스path, 출력path, 검색결과파일, 연관검색여부(a)	
		if ( ! -e $sfile ) {
			print STDERR "!! $sfile 를 찾을수 없습니다.\n" ;
			return 9; 
		}
		mkdir $wdir ;
		
		if  ( ! -d $wdir ) {
			print STDERR "!! $wdir 은 diretory가 아닙니다.\n"	;
			return 9; 
		}
		$src_path =~ s!\\!/!g;
		mkdir $wdir.'/list' ;
		
		my $stime = time;
		
		my $sltm = localtime ;
		print STDERR "\n*** Start $0: $sltm \n";
				
		&dwtstyle_css($wdir);
		
		open $Ftbl,'>',$wdir.'/overview-tbl.html' || print STDERR "(tbl) $! \n" && return 8;
		open $Fcol,'>',$wdir.'/allcollist.html' || print STDERR "(col) $! \n" && return 8 ;
		
		write_h($Ftbl,"테이블") ;
		write_h($Fcol,"칼럼") ;
		
		$T_COUNT = 0;

		gen_html() ;
		
		write_f($Ftbl) ;
		write_f($Fcol) ;

		write_f($Flst) if ($Flst);

		close $Ftbl;
		close $Fcol;
		close $Flst if ($Flst);
		&html_overview();
		
#		copy($First_html,$wdir.'/alllist.html') if ( $First_html  );
		
		$sltm = localtime ;
		print "\n***   End $0: $sltm \n";
}

sub gen_html {
    my $count = 0;

    open my $F1,"<", $sfile ;
    my $shead = <$F1>;  
    chomp($shead) ;

    while( <$F1> ) {
      chomp;
      $count++;

      my $row;
      @$row = split( /\t/, $_ );
      push @$sheet, $row;
    }

    close $F1;
    return unless $count ;
    
	if ($ftype eq 'a') {
    	@$sheet = sort { $a->[0] cmp $b->[0] || $a->[1] cmp $b->[1] || $a->[8] <=>  $b->[8] || $a->[3] cmp $b->[3]} @$sheet ;
    } else {
    	@$sheet = sort { $a->[0] cmp $b->[0] || $a->[1] cmp $b->[1] || $a->[3] cmp $b->[3]} @$sheet ;
    }
    
    my ($stbl, $scol, $spath, $num) = (" "," "," ",0) ;

    print "\n";
    foreach my $row ( @$sheet ) {
    	$row->[0] = '미확인' unless ($row->[0]) ;
    	if ($stbl ne $row->[0]) {
    		$stbl = $row->[0] ;
    		$scol = $row->[1] ;
    		write_tbl($stbl) ;
    		write_col($stbl,$scol) ;
    		write_list_h($stbl,$scol,$shead) ;
    		$num = 0 ;
    	} elsif ($scol ne $row->[1]) {
    		$scol = $row->[1] ;
    		write_col($stbl,$scol) ;
    		write_list_h($stbl,$scol,$shead) ;
    		$num = 0 ;
    	}
    	$num++ ;
		print {$Flst} qq(<TR BGCOLOR="white" CLASS="TableRowColor"><TD ALIGN="center">$num</TD>\n) ;
#		print {$Flst} qq(<TD style="word-break:break-all">$row->[1]</TD>)  if ($ftype ne 'a') ;
		$spath = "$src_path/$row->[2]/$row->[3]" ;
		$spath =~ s!//!/!g ;
		print {$Flst} <<END;
		<TD style="word-break:break-all">$row->[2]</TD>
		<TD  style="word-break:nowrap"><A href="$spath" onclick="viewthesource(this.href); return false;">$row->[3]</A></TD>
		<TD ALIGN="center" >$row->[4]</TD>
		<TD style="word-break:break-all">$row->[5]</TD>
END
		print {$Flst} qq(<TD style="word-break:break-all">$row->[6]</TD>) if $row->[6];
		print "@$row","\n" unless $row->[2] || $row->[3] || $row->[4] || $row->[5] || $row->[6] ;
    	print {$Flst} qq(<TD style="word-break:break-all">$row->[7]</TD>\n) if $row->[7];
    	print {$Flst} qq(<TD ALIGN="center">$row->[8]</TD>\n) if $row->[8];
		print {$Flst} "</TR>\n";
    }	
}

sub write_h {
my ($FH, $title) = @_ ;
my $sdate=Dawin::getstrdate("-");
print {$FH} <<END;
<!DOCTYPE HTML>
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by dwgenHTML on `localtime` -->
<META http-equiv="Content-Type" content="text/html; charset=euc-kr">
<TITLE>
$title 리스트 </TITLE>

<META NAME="date" CONTENT="$sdate">

<LINK REL ="stylesheet" TYPE="text/css" HREF="dwtstyle.css" TITLE="Style">


</HEAD>

<BODY BGCOLOR="white">
<HR>
<FONT color="indigo" >
<B>$title 목록</B></FONT>
END

}

sub write_list_h {
my ($tbl, $col) = @_ ;
my @items = split /\t/,$_[2] ;

write_f($Flst) if ($Flst);

close $Flst if ($Flst);

my $fnm = $wdir.'/list/'.$tbl.$col.'.html' ;
$First_html = 'list/'.$tbl.$col.'.html' unless $T_COUNT ;

$T_COUNT++ ;
print  "* 처리건수 *--> $T_COUNT		\r";
open $Flst,'>', $fnm or die "($fnm)$! \n" ;

my $sdate=Dawin::getstrdate("-");
my $width = ($ftype eq 'a' ? '120%' : '100%') ;
print {$Flst} <<END;
<!DOCTYPE HTML>
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by dwgenHTML on `localtime` -->
<META http-equiv="Content-Type" content="text/html; charset=euc-kr">
<TITLE>
프로그램 리스트 </TITLE>

<META NAME="date" CONTENT="$sdate">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../dwtstyle.css" TITLE="Style">
<LINK REL ="stylesheet" TYPE="text/css" HREF="dwtstyle.css" TITLE="Style">

<script> 
function viewthesource(url) { 
	if (navigator.userAgent.toLowerCase().indexOf('msie') != -1) {
		window.open(url,'','');
	} else {
		window.open('view-source:'+ url,'','');
	} ;
} 
</script> 

</HEAD>

<BODY BGCOLOR="white">

<FONT CLASS="FrameTitleFont">
<B>[ $tbl : $col ]</B></FONT>
<TABLE BORDER="1" WIDTH="$width" CELLSPACING="1" SUMMARY="" bordercolor="silver" >
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TH width="5%">No</TH>
END

#  print {$Flst} qq(<TH nowrap ALIGN="center" >$items[1]</TH>\n)  if ($ftype ne 'a') ;
	for my $i (2..$#items) {
	  my $wd = ($i == 5 ? 'width="40%"' : ($i == 4 ? 'width="5%"' : '')) ;
	  print {$Flst} qq(<TH nowrap $wd ALIGN="center" >$items[$i]</TH>\n)  ;
	}
	print {$Flst} "</TR>\n" ;

}

sub write_tbl {
	my $tbl = $_[0] ;
	print {$Ftbl} <<END;
<BR>
<FONT CLASS="FrameItemFont"><A HREF="allcollist.html#$tbl" target="colListFrame">$tbl</A> </FONT>
END
	print {$Fcol} <<END;
		<BR><A name="$tbl"><BR><FONT color="olive"><B>$tbl</B></FONT></A>
END
}

sub write_col {
	my ($tbl,$col) = @_ ;
	my $html = 'list/'.$tbl.$col.'.html';
	print {$Fcol} <<END;
<BR>&nbsp;
<FONT CLASS="FrameItemFont"><A HREF="$html" target="ListFrame">$col</A> </FONT>
END

}

sub write_f {
my ($FH) = @_ ;
print {$FH} <<END;
</TABLE>
</BODY>
</HTML>
END

}

sub html_overview {
  my $fname = $wdir.'/overview-main.html';
  open( my $FH,">",$fname) or die "$fname $! \n";
print $FH <<HO_END;
<!DOCTYPE HTML>
<!--NewPage-->
<HTML>
<HEAD>

<META http-equiv="Content-Type" content="text/html; charset=euc-kr">

<TITLE>
다윈ICT finder V1.0
 - </TITLE>
<SCRIPT type="text/javascript">
    targetPage = "" + window.location.search;
    if (targetPage ! = "" && targetPage ! = "undefined")
       targetPage = targetPage.substring(1);
    function loadFrames() {
        if (targetPage ! = "" && targetPage ! = "undefined")
             top.classFrame.location = top.targetPage;
    }
</SCRIPT>
<NOSCRIPT>
</NOSCRIPT>
</HEAD>
<FRAMESET cols="20%,80%" title="" frameborder="1" onLoad="top.loadFrames()">
<FRAMESET rows="40%,60%" title="" frameborder="1" onLoad="top.loadFrames()">
<FRAME src="overview-tbl.html" name="tblListFrame" title="모든 테이블">
<FRAME src="allcollist.html" name="colListFrame" title="칼럼목록">
</FRAMESET>
<FRAME src="$First_html" name="ListFrame" title="테이블/칼럼 관련프로그램" scrolling="yes">
<NOFRAMES>
<H2>
프레임 관련의 경고</H2>

<P>
이 문서는 프레임 기능을 사용해 표시하도록(듯이) 만들어지고 있습니다. 프레임을 표시할 수 없는 Web 클라이언트의 경우에 이 메세지가 표시됩니다.
<BR>
링크처<A HREF="alllist.html">프레임 없음의 버젼</A> 
</NOFRAMES>
</FRAMESET>
</HTML>
HO_END

close $FH;
}

sub dwtstyle_css($) {
  my $fname = (shift) .'/dwtstyle.css';
  open( my $FH,">",$fname) or die "$fname $! \n";
print $FH <<'CSS_END';
body { font-family: 맑은고딕, Arial, sans-serif; background-color: #FFFFFC; color:#000000 }

h1 { font-size: 145% }
th {font-family: 맑은고딕; font-size: 90%}
td {font-family: 맑은고딕; font-size: 90%; vertical-align:top }

.TableHeadingColor     { background: #CCCCFF; color:#000000 } 
.TableSubHeadingColor  { background: #EEEEFF; color:#000000 } 
.TableRowColor         { background: #FFFFFF; color:#000000 } 

.FrameTitleFont   { font-size: 100%; font-family: 맑은고딕, Arial, sans-serif; color:olive }
.FrameHeadingFont { font-size:  90%; font-family: 맑은고딕, Arial, sans-serif; color:#000000 }
.FrameItemFont    { font-size:  80%; font-family: 맑은고딕, Arial, sans-serif; color:#000000 }

.NavBarCell1    { background-color:#EEEEFF; color:#000000} 
.NavBarCell1Rev { background-color:#00008B; color:#FFFFFF} 
.NavBarFont1    { font-family: 맑은고딕, Helvetica, sans-serif; color:#000000;color:#000000;}
.NavBarFont1Rev { font-family: 맑은고딕, Helvetica, sans-serif; color:#FFFFFF;color:#FFFFFF;}

.NavBarCell2    { font-family: 맑은고딕, Helvetica, sans-serif; background-color:#FFFFFF; color:#000000}
.NavBarCell3    { font-family: 맑은고딕, Helvetica, sans-serif; background-color:#FFFFFF; color:#000000}
CSS_END

close $FH;
}
1;